//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace allinthebox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("allinthebox.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string addButton {
            get {
                return ResourceManager.GetString("addButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien.
        /// </summary>
        internal static string allFilesType {
            get {
                return ResourceManager.GetString("allFilesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jährlich.
        /// </summary>
        internal static string annually {
            get {
                return ResourceManager.GetString("annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beim nächsten Start.
        /// </summary>
        internal static string atNextStart {
            get {
                return ResourceManager.GetString("atNextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoBackup.
        /// </summary>
        internal static string autoBackup {
            get {
                return ResourceManager.GetString("autoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verfügbar.
        /// </summary>
        internal static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurückgeben.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupManager.
        /// </summary>
        internal static string BackupManager {
            get {
                return ResourceManager.GetString("BackupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuell Sichern.
        /// </summary>
        internal static string backupManually {
            get {
                return ResourceManager.GetString("backupManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcodefarbe.
        /// </summary>
        internal static string barcodeColor {
            get {
                return ResourceManager.GetString("barcodeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausleihen.
        /// </summary>
        internal static string borrow {
            get {
                return ResourceManager.GetString("borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entliehen.
        /// </summary>
        internal static string borrowed {
            get {
                return ResourceManager.GetString("borrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entliehene Items kursiv.
        /// </summary>
        internal static string borrowedItalic {
            get {
                return ResourceManager.GetString("borrowedItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entliehenes hervorheben.
        /// </summary>
        internal static string borrowedMarked {
            get {
                return ResourceManager.GetString("borrowedMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entliehenes Auswahlfarbe.
        /// </summary>
        internal static string borrowMarkedSelectedColor {
            get {
                return ResourceManager.GetString("borrowMarkedSelectedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlage Auswählen.
        /// </summary>
        internal static string choosePreset {
            get {
                return ResourceManager.GetString("choosePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkung.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkungsfarbe.
        /// </summary>
        internal static string commentColor {
            get {
                return ResourceManager.GetString("commentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to täglich.
        /// </summary>
        internal static string daily {
            get {
                return ResourceManager.GetString("daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du wirklich alle Error einträge löschen?.
        /// </summary>
        internal static string deleteError {
            get {
                return ResourceManager.GetString("deleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du die Zeile wirklich Löschen?.
        /// </summary>
        internal static string deleteLine {
            get {
                return ResourceManager.GetString("deleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du wirklich alle Log einträge löschen?.
        /// </summary>
        internal static string deleteLog {
            get {
                return ResourceManager.GetString("deleteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument.
        /// </summary>
        internal static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doku.
        /// </summary>
        internal static string doku {
            get {
                return ResourceManager.GetString("doku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort oder Nutzername sind falsch....
        /// </summary>
        internal static string errorCredentialsWrong {
            get {
                return ResourceManager.GetString("errorCredentialsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errorspeicher gelöscht.
        /// </summary>
        internal static string errorDeleted {
            get {
                return ResourceManager.GetString("errorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte beide Felder ausfüllen....
        /// </summary>
        internal static string errorEmpty {
            get {
                return ResourceManager.GetString("errorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorLog {
            get {
                return ResourceManager.GetString("errorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exakte Barcodesuche.
        /// </summary>
        internal static string exactBarcode {
            get {
                return ResourceManager.GetString("exactBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceltabelle.
        /// </summary>
        internal static string excel {
            get {
                return ResourceManager.GetString("excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlassen.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei existiert bereits!.
        /// </summary>
        internal static string fileAlreadyExists {
            get {
                return ResourceManager.GetString("fileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei erstellt..
        /// </summary>
        internal static string fileCreated {
            get {
                return ResourceManager.GetString("fileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wurde erfolgreich gespeichert..
        /// </summary>
        internal static string fileSavedSentence_2 {
            get {
                return ResourceManager.GetString("fileSavedSentence_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftart.
        /// </summary>
        internal static string fontColor {
            get {
                return ResourceManager.GetString("fontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftgröße.
        /// </summary>
        internal static string fontSize {
            get {
                return ResourceManager.GetString("fontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gefunden.
        /// </summary>
        internal static string found {
            get {
                return ResourceManager.GetString("found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastenkombinationen.
        /// </summary>
        internal static string hotKeys {
            get {
                return ResourceManager.GetString("hotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilddateien.
        /// </summary>
        internal static string imageFiles {
            get {
                return ResourceManager.GetString("imageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildvollansicht immer oben.
        /// </summary>
        internal static string imageOnTop {
            get {
                return ResourceManager.GetString("imageOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Rechte an diesem Programm liegen bei Lukas Schreiber | Polymation. Das Vervielfältigen des Programmes sowie das Verkaufen dieser Lizenz ist widersagt. Weitere Lizenzen können auf der Patreonseite des Programmes erworben werden. Vielen Dank an Miriam Janßen für die Unterstützung und Inspiration für dieses Programm, sowie an Mathis Kaiser für die französische und Friederike Escher für die spanische Übersetzung..
        /// </summary>
        internal static string infotext {
            get {
                return ResourceManager.GetString("infotext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string itemAddButton {
            get {
                return ResourceManager.GetString("itemAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sowohl das Feld Barcode als auch Name dürfen nicht leer sein..
        /// </summary>
        internal static string itemAddErrorEmpty {
            get {
                return ResourceManager.GetString("itemAddErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier steht ein Witz (-:.
        /// </summary>
        internal static string joke {
            get {
                return ResourceManager.GetString("joke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes Backup.
        /// </summary>
        internal static string lastBackup {
            get {
                return ResourceManager.GetString("lastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lukas Schreiber auf LinkedIn.
        /// </summary>
        internal static string linkedIn {
            get {
                return ResourceManager.GetString("linkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausleihliste.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausleihliste von.
        /// </summary>
        internal static string listSentence_1 {
            get {
                return ResourceManager.GetString("listSentence_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erstellt am.
        /// </summary>
        internal static string listSentence_2 {
            get {
                return ResourceManager.GetString("listSentence_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlage Laden.
        /// </summary>
        internal static string loadPreset {
            get {
                return ResourceManager.GetString("loadPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log gelöscht.
        /// </summary>
        internal static string logDeleted {
            get {
                return ResourceManager.GetString("logDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angemeldet als.
        /// </summary>
        internal static string loggedInAs {
            get {
                return ResourceManager.GetString("loggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        internal static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile Statusänderung.
        /// </summary>
        internal static string menuBorrow {
            get {
                return ResourceManager.GetString("menuBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile löschen.
        /// </summary>
        internal static string menuDeleteRow {
            get {
                return ResourceManager.GetString("menuDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Länge.
        /// </summary>
        internal static string minLength {
            get {
                return ResourceManager.GetString("minLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monatlich.
        /// </summary>
        internal static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiAuswahlTool.
        /// </summary>
        internal static string MultiAuswahlTool {
            get {
                return ResourceManager.GetString("MultiAuswahlTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namensfarbe.
        /// </summary>
        internal static string nameColor {
            get {
                return ResourceManager.GetString("nameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Nutzer existiert bereits..
        /// </summary>
        internal static string namingViolation {
            get {
                return ResourceManager.GetString("namingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie.
        /// </summary>
        internal static string never {
            get {
                return ResourceManager.GetString("never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Nutzer.
        /// </summary>
        internal static string newUser {
            get {
                return ResourceManager.GetString("newUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächstes Backup.
        /// </summary>
        internal static string nextBackup {
            get {
                return ResourceManager.GetString("nextBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Item ausgewählt.
        /// </summary>
        internal static string noItem {
            get {
                return ResourceManager.GetString("noItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Ergebnisse.
        /// </summary>
        internal static string noResults {
            get {
                return ResourceManager.GetString("noResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Zeile ausgewählt.
        /// </summary>
        internal static string noRowSelected {
            get {
                return ResourceManager.GetString("noRowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen nur bei Scannerwechsel vornehmen!.
        /// </summary>
        internal static string noteScanner {
            get {
                return ResourceManager.GetString("noteScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurzeit ist nichts ausgewählt.
        /// </summary>
        internal static string nothingSelected {
            get {
                return ResourceManager.GetString("nothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht Angemeldet.
        /// </summary>
        internal static string notLoggedIn {
            get {
                return ResourceManager.GetString("notLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein USB Stick.
        /// </summary>
        internal static string noUsb {
            get {
                return ResourceManager.GetString("noUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenster jeweils nur einmal öffnen.
        /// </summary>
        internal static string openOnce {
            get {
                return ResourceManager.GetString("openOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort und Nutzername müssen ausgefüllt sein!.
        /// </summary>
        internal static string passwordAndUserFilled {
            get {
                return ResourceManager.GetString("passwordAndUserFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        internal static string picture {
            get {
                return ResourceManager.GetString("picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leere Vorlage.
        /// </summary>
        internal static string preset {
            get {
                return ResourceManager.GetString("preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlage.
        /// </summary>
        internal static string presetType {
            get {
                return ResourceManager.GetString("presetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primärfarbe.
        /// </summary>
        internal static string primeColor {
            get {
                return ResourceManager.GetString("primeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertung.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei aktualisiert..
        /// </summary>
        internal static string refreshedFile {
            get {
                return ResourceManager.GetString("refreshedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regal.
        /// </summary>
        internal static string regal {
            get {
                return ResourceManager.GetString("regal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du das Regal wirklich Löschen?.
        /// </summary>
        internal static string regalDelete {
            get {
                return ResourceManager.GetString("regalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regalfach.
        /// </summary>
        internal static string regalfach {
            get {
                return ResourceManager.GetString("regalfach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regalmanager.
        /// </summary>
        internal static string regalmanager {
            get {
                return ResourceManager.GetString("regalmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um die Regale zuzuordnen, kann man diese links bearbeiten und frei auf dem Bild umher verschieben.  Das Hintergrundbild kann in Paint zum Beispiel erstellt werden. Dazu einfach die Vorlage speichern..
        /// </summary>
        internal static string regalManagerDescribe {
            get {
                return ResourceManager.GetString("regalManagerDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Ursprung zurücksetzen.
        /// </summary>
        internal static string resetHotkeys {
            get {
                return ResourceManager.GetString("resetHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellen.
        /// </summary>
        internal static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup erfolgreich geladen..
        /// </summary>
        internal static string restoreOk {
            get {
                return ResourceManager.GetString("restoreOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regalmanager immer oben.
        /// </summary>
        internal static string rmOnTop {
            get {
                return ResourceManager.GetString("rmOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Dokument speichern.
        /// </summary>
        internal static string saveAsDoc {
            get {
                return ResourceManager.GetString("saveAsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlage Speichern.
        /// </summary>
        internal static string savePreset {
            get {
                return ResourceManager.GetString("savePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherabfrage.
        /// </summary>
        internal static string saveQuestion {
            get {
                return ResourceManager.GetString("saveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcodescanner.
        /// </summary>
        internal static string scanner {
            get {
                return ResourceManager.GetString("scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum ersten Ergebnis scrollen.
        /// </summary>
        internal static string scrollToFirst {
            get {
                return ResourceManager.GetString("scrollToFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode suchen.
        /// </summary>
        internal static string searchBarcode {
            get {
                return ResourceManager.GetString("searchBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkungen suchen.
        /// </summary>
        internal static string searchComments {
            get {
                return ResourceManager.GetString("searchComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen suchen.
        /// </summary>
        internal static string searchNames {
            get {
                return ResourceManager.GetString("searchNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucheinstellungen.
        /// </summary>
        internal static string searchSettings {
            get {
                return ResourceManager.GetString("searchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchstandard.
        /// </summary>
        internal static string searchStandard {
            get {
                return ResourceManager.GetString("searchStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen während Tippen.
        /// </summary>
        internal static string searchWhileTyping {
            get {
                return ResourceManager.GetString("searchWhileTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekundärfarbe.
        /// </summary>
        internal static string secondColor {
            get {
                return ResourceManager.GetString("secondColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahlfarbe.
        /// </summary>
        internal static string selectColor {
            get {
                return ResourceManager.GetString("selectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiAuswahltool immer oben.
        /// </summary>
        internal static string selectOnTop {
            get {
                return ResourceManager.GetString("selectOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen immer oben.
        /// </summary>
        internal static string settingsOnTop {
            get {
                return ResourceManager.GetString("settingsOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umschalttaste.
        /// </summary>
        internal static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string suffix {
            get {
                return ResourceManager.GetString("suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix Minimum.
        /// </summary>
        internal static string suffixSendMin {
            get {
                return ResourceManager.GetString("suffixSendMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Closing.
        /// </summary>
        internal static string systemClose {
            get {
                return ResourceManager.GetString("systemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabellenDesign.
        /// </summary>
        internal static string tableDesign {
            get {
                return ResourceManager.GetString("tableDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabellenansicht.
        /// </summary>
        internal static string tableView {
            get {
                return ResourceManager.GetString("tableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haken.
        /// </summary>
        internal static string tick {
            get {
                return ResourceManager.GetString("tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhr.
        /// </summary>
        internal static string timeFormat {
            get {
                return ResourceManager.GetString("timeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzer.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzermanager.
        /// </summary>
        internal static string userManager {
            get {
                return ResourceManager.GetString("userManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzername.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternativ USB Schlüssel verwenden....
        /// </summary>
        internal static string useUSB {
            get {
                return ResourceManager.GetString("useUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du die Liste als Datei speichern?.
        /// </summary>
        internal static string wantToSave {
            get {
                return ResourceManager.GetString("wantToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wöchentlich.
        /// </summary>
        internal static string weekly {
            get {
                return ResourceManager.GetString("weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximieren.
        /// </summary>
        internal static string windowMaximize {
            get {
                return ResourceManager.GetString("windowMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimieren.
        /// </summary>
        internal static string windowMinimize {
            get {
                return ResourceManager.GetString("windowMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkleinern.
        /// </summary>
        internal static string windowNormal {
            get {
                return ResourceManager.GetString("windowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenstereinstellungen.
        /// </summary>
        internal static string windowSerttings {
            get {
                return ResourceManager.GetString("windowSerttings", resourceCulture);
            }
        }
    }
}
